### ISSUE TITLE
daemon port (18560) conflicts with seno's harverster_rpc port

### ISSUE THREAD

**Issue by rwarren** [Salvia-Network/salvia-blockchain#11]
Your choice of daemon port conflicts with the seno's established (long ago!) harvester RPC port.  This is a major problem for people farming multiple forks in the same environment.

Please fix this in your next release, and either A) inform people that the port needs to be changed in their local mainnet config, or B) automate said port switch on update.

For reference, we keep a full chia port conflict list here online:
https://docs.google.com/spreadsheets/d/1ttIK-TQwwWeY4XarapjKAYJIgDJ5Kk9yjvBPLIlrpdg/edit#gid=1006768047

**Comment by Salvia-Network** [comment]
Thanks for notification, I will escalate port alter request now, it will be changed soon

**Comment by Salvia-Network** [comment]
Issue is fixed in release 0.7.1
