### ISSUE TITLE
Please share Nodes. thanks

### ISSUE THREAD

**Issue by zfung03** [Salvia-Network/salvia-blockchain#9]
Please share Nodes. thanks

**Comment by ageorge95** [comment]
FULL_NODE 109.236.48.163                         18520/18520 0b251a2f... Sep 28 07:58:05     11.1|162.4  
                                                 -SB Height:    38582    -Hash: 6f866785...
FULL_NODE 86.63.197.242                          18520/18520 220c88d4... Sep 28 07:58:05     34.6|114.8  
                                                 -SB Height:    38582    -Hash: 6f866785...
FULL_NODE 47.135.246.140                         18520/18520 4d396fed... Sep 28 07:58:05     40.7|8.8    
                                                 -SB Height:    38582    -Hash: 6f866785...
FULL_NODE 49.49.30.106                           18520/18520 774afb55... Sep 28 07:58:02     27.5|23.1   
                                                 -SB Height:    38582    -Hash: 6f866785...
FULL_NODE 2a00:1028:8398:5446:1514:50f1:2317:a30 18520/18520 dc170a60... Sep 28 07:58:05     16.9|10.5   
                                                 -SB Height:    38582    -Hash: 6f866785...
FULL_NODE 61.56.182.69                           18520/18520 3217e975... Sep 28 07:58:02      7.1|3.9    
                                                 -SB Height:    38582    -Hash: 6f866785...
FULL_NODE 2403:6200:8996:6ce:2186:13c:9fa2:fea0] 18520/18520 94977349... Sep 28 07:58:03      6.9|2.1    
                                                 -SB Height:    38582    -Hash: 6f866785...
FULL_NODE 37.1.48.63                             18520/18520 2767c043... Sep 28 07:58:05      0.4|5.5    
                                                 -SB Height:    38582    -Hash: 6f866785...
